import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { authReach} from '../Context/ReachContext'

export default function Home() {
    console.log("HOME")
    const {login,hasUser} = authReach()
    const themeStyle = {
        backgroundColor: hasUser ? "green" : "purple"
    }
  return (
    <div className={styles.container} style={themeStyle}>
      <Head>
        <title>JASIRI PROTOCOL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={()=>login()}>CONNECT WALLET</button>
      <br></br>
      <Link href={"/AdminView"}>ADMINVIEW</Link>
      <br></br>
      <Link href={"/Tokenizer"}>TOKENIZEVIEW</Link>
      <br></br>
      <Link href={"/GetJasiris"}>GetJASIRIS</Link>
      <br></br>
      <Link href={"/Market"}>Market</Link>
      <br></br>
      <Link href={"/Bidder"}>Bidder</Link>
      <br></br>
      <Link href={"/PoolView"}>Pool</Link>
    </div>
  )
}